module.exports = {
	purge: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
	darkMode: 'class', // or 'media' or 'class'
	theme: {
		extend: {
			colors: {
				// ten-cua-mau: ma-mau-hex
				primary: '#3ABD98',
				secondary: '#4dc5a3',
				tertiary: '#7ed7be',
				light: '#baebdd',
				lighter: '#d9f4ed',
				'lighter-alt': '#f5fcfa',
				darker: '#216a55',
				dark: '#2c8f73',
				'dark-alt': '#35aa89',
				'neutral-dark': '#201f1e',
				'neutral-primary': '#323130',
				'neutral-primary-alt': '#3b3a39',
				'neutral-secondary': '#605e5c',
				'neutral-tertiary': '#a19f9d',
				'neutral-tertiary-alt': '#c8c6c4',
				'neutral-quaternary': '#d0d0d0',
				'neutral-quaternary-alt': '#E1E7EB',
				'neutral-light': '#edebe9',
				'neutral-lighter': '#f3f2f1',
				'neutral-lighter-alt': '#faf9f8',
				error: '#ED4337',
				'light-grey': '#d3cfca',
				'neutral-lighter-tertiary-alt': '#F4F4F4',
			},
			spacing: {
				// ten: kich thuoc mong muon - px, rem, em, % ...
				sm: '0.30rem',
				md: '0.45rem',
				xs: '0.01rem',
				'5p': '5%',
				'10p': '10%',
				'15p': '15%',
				'20p': '20%',
				'25p': '25%',
				'30p': '30%',
				'35p': '35%',
				'40p': '40%',
				'45p': '45%',
				'50p': '50%',
				'55p': '55%',
				'60p': '60%',
				'65p': '65%',
				'70p': '70%',
				'75p': '75%',
				'80p': '80%',
				'85p': '85%',
				'90p': '90%',
				'95p': '95%',
				sbp: '440px',
				ip: '150px',
				86: '330px',
				ava: '65px',
				msb: '15px',
				total: '80px',
			},
			borderRadius: {
				md: '0.25rem',
				ttb: '1.5rem',
				lg: '3rem',
			},
			fontSize: {
				title: '1.5rem',
			},
			width: {
				'an-item': '30%',
			},
			scale: {
				'-1': '-1',
			},
		},
	},
	variants: {
		extend: {
			outline: ['active'],
			textColor: ['visited'],
			backgroundColor: ['active'],
			borderRadius: ['last', 'first'],
		},
	},
	plugins: [],
}
