const COOKIE_KEY = {
	AUTH_TOKEN: 'authToken',
}

const MIDDLE_DISPATCH_ACTION_CONSTANTS = {
	ASYNC_START: 'ASYNC_START',
	ASYNC_END: 'ASYNC_END',

	REGISTER_SUCCESS: 'REGISTER_SUCCESS',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOAD_USER_ERROR: 'LOAD_USER_ERROR',
	LOGOUT: 'LOGOUT',
}

export default {
	COOKIE_KEY,
	MIDDLE_DISPATCH_ACTION_CONSTANTS,
}
